### ISSUE TITLE
有没有精力考虑将osd歌词作为单独软件形式发布？

### ISSUE THREAD

**Issue by warmsun0220** [LiuLang/kwplayer#72]
类似osdlyrics那种…linux下缺这个缺好久了。或者帮助更新一下osdlyric。
感谢你…只是建议，可以直接把这个issue关闭。

**Comment by LiuLang** [comment]
kwplayer是支持OSDLyrics插件的, 之前有朋友提交了一个补丁.
但OSDLyrics很久没人维护了.

kwplayer里面的OSD模块很独立, 只需要稍加处理就可以嵌到其它播放器中.

**Comment by warmsun0220** [comment]
osdlyric其实做的挺完善的  但是太久没人维护。新版在我这一直有关闭播放器后osdlyric又重新启动的bug，挺闹心的。
用过kwplayer的歌词，感觉还是挺好的，平时离线比较多，所以才来咨询一下能不能做成单独的类似osdlyric的软件。
毕竟精力也有限，把KWplayer坚持下去就很好了，感谢。
