### ISSUE TITLE
kwplayer 快捷键问题

### ISSUE THREAD

**Issue by dengdairiluo** [LiuLang/kwplayer#73]
系统 Ubuntu14.04LTS 
软件版本 349
同样是使用默认的多媒体快捷键
系统重装之后不支持笔记本多媒体快捷键 但能够在自定义快捷键下识别笔记本快捷键

**Comment by LiuLang** [comment]
请确认已经安装了python3-keybinder, python3-xlib这两个包. https://github.com/LIuLang/kwplayer-packages

**Comment by LiuLang** [comment]
请确认已经安装了python3-keybinder, python3-xlib这两个包. https://github.com/LIuLang/kwplayer-packages
