### ISSUE TITLE
问下，这个酷获得官方授权了吗？如何联系他们呢

### ISSUE THREAD

**Issue by xsjqqq123** [LiuLang/kwplayer#75]
我最近写的一个手机助手，将酷我音乐融进去了，可有些怕没授权被ko啊，您这个的情况怎样的？

**Comment by LiuLang** [comment]
你说的那个"酷我音乐" 是哪来的? 是修改(破解)了酷我音乐官方的apk程序然后再次发布? 如果这样的话, 是侵犯了kuwo.cn
的著作权的(你可以读一下它的License).

但这个kwplayer没有使用一行酷我音乐的代码, 都是自己写的, 只是读取了它的服务器上的一些开放资源, 比如mp3文件.
而kuwo.cn本身并不持有这些文件的版权,
换句话说, 它服务器上存储的有好多都是盗版资源.

LiuLang

2015-01-30 0:40 GMT+08:00 xsjqqq123 <notifications@github.com>:

**Comment by xsjqqq123** [comment]
那就好，我用的是它那在线音乐播放器里边的地址。我在deepin上装您那个deb包时，播放时提示"glib error 安装缺少插件gst-core-error-quark"

**Comment by LiuLang** [comment]
没在deepin 里面测试过, 不晓得什么情况. deepin好像改了不少东西, 而且deepin软件库里的kwplayer已经快一年没更新了.
