### ISSUE TITLE
请问源码打包的时候出现的错误提示如何解决

### ISSUE THREAD

**Issue by qingsword** [LiuLang/kwplayer#77]
使用 dpkg-checkbuilddeps检查到两个关联包都装上后，打包出现下面的提示
-----------------------------------------------------
~/test/kwplayer$ sudo dpkg-buildpackage 
dpkg-buildpackage: 源码包 kwplayer
dpkg-buildpackage: 源码版本 3.5.1-1
dpkg-buildpackage: source distribution stable
dpkg-buildpackage: 源码修改者 Liu Lang <gsushzhsosgsu@gmail.com>
dpkg-buildpackage: 主机架构 amd64
 dpkg-source --before-build kwplayer
 debian/rules clean
dh clean --with python3  --buildsystem=pybuild
   dh_testdir -O--buildsystem=pybuild
   dh_auto_clean -O--buildsystem=pybuild
I: pybuild base:170: python3.4 setup.py clean 
running clean
removing '/home/hey/test/kwplayer/.pybuild/pythonX.Y_3.4/build' (and everything under it)
'build/bdist.linux-x86_64' does not exist -- can't clean it
'build/scripts-3.4' does not exist -- can't clean it
   dh_clean -O--buildsystem=pybuild
 dpkg-source -b kwplayer
dpkg-source: 错误: can't build with source format '3.0 (quilt)': no upstream tarball found at ../kwplayer_3.5.1.orig.tar.{bz2,gz,lzma,xz}
dpkg-buildpackage: 错误: dpkg-source -b kwplayer 提供错误退出状态 255
----------------
请问是否我的方法不正确？

**Comment by LiuLang** [comment]
不正确.
你没有kwplayer_3.5.1.orig.gz 这个压缩包, 而且, 目录名也不匹配.
如果要学习制作deb包的话, 可以到debian.org上找一些文档, 里面有说明.

**Comment by qingsword** [comment]
好的～感谢～
