### ISSUE TITLE
Ubuntu 14.04 设置音乐格式为Flac出错

### ISSUE THREAD

**Issue by mhohai** [LiuLang/kwplayer#78]
![flac](https://clbin.com/nHrsTy.png)
![error](https://clbin.com/Dd7buW.png)
设置后，下次开机又变为320K。log: `WARNING module `mutagen` was not found!`

- [ ] 搜索页面，建议支持Ctrl，Shift复选，批量添加下载操作

**Comment by mhohai** [comment]
歌曲名带后缀: ?src=kwplayer_ar
![歌曲名带后缀](https://clbin.com/B4GTJU.png)

设置锁屏时显示，播放歌曲时弹出:
![锁屏显示，播放弹出](https://clbin.com/CNGuuu.png)

**Comment by LiuLang** [comment]
On 03/12/2015 08:48 AM, gshmu wrote:
> 歌曲名带后缀: ?src=kwplayer_ar
> ![歌曲名带后缀](https://clbin.com/B4GTJU.png)
>
> 设置锁屏时显示，播放歌曲时弹出:
> ![锁屏显示，播放弹出](https://clbin.com/CNGuuu.png)
>
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/LiuLang/kwplayer/issues/78#issuecomment-78404307
>

播放时弹出的通知, 那个你没有看清楚"首选项"中的说明. 桌面通知选项只用于 
gnome shell桌面, 其它桌面环境比如unity等, 是不能启用那个选项的, 不然会连 
续弹出类似的通知.

关于文件名的问题, 我会确认一下的, 谢谢你的反馈.

**Comment by mhohai** [comment]
有几个图下面都有一行说明，或好 或不好的解决问题…

我有点儿想自己解决，可有点儿像无头苍蝇。。。  
再反馈个现象，我`$ pip3 install gi`, 然后kwpalyer挂了，卸了gi又好了

**Comment by LiuLang** [comment]
On 03/13/2015 08:25 AM, gshmu wrote:
> 有几个图下面都有一行说明，或好 或不好的解决问题…
>
> 我有点儿想自己解决，可有点儿像无头苍蝇。。。
> 再反馈个现象，我`$ pip3 install gi`, 然后kwpalyer挂了，卸了gi又好了
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/LiuLang/kwplayer/issues/78#issuecomment-78712669
>

刚开始几句没大明白 ;(-

干嘛手动安装gi模块? 软件库里面有, 而且如果用kwplayer的deb包来安装的话, 
它会自动处理好依赖关系的, 不需要手动安装gi了.

**Comment by LiuLang** [comment]
https://github.com/LiuLang/kwplayer/issues/78#issue-60234776
这个问题, 在v3.5.1中已经修复了, 但之前忘记打包了, 所以在v3.4.9中仍然存在, 今天会打包v3.5.2.

另外你说的flac出错的问题, 我在ubuntu 14.04.2 amd64中测试了, 是可以正常使用flac格式的.

**Comment by mhohai** [comment]
flac使用是正常的，是设置后保存会报错。
log：`WARNING module `mutagen` was not found!`  我手动装了mutagen包还是报错。 可能是这个包的依赖问题。

我安装了deb是好的，正常工作，我多装了个包：`sudo pip3 install gi` 然后就挂了
> ~$ kwplayer 
Traceback (most recent call last):
  File "/usr/bin/kwplayer", line 13, in <module>
    from gi.repository import Gtk
  File "/usr/local/lib/python3.4/dist-packages/gi/__init__.py", line 39
    print url
            ^
SyntaxError: invalid syntax


卸载这个包就正常了，是不是这个包我装的有问题？ 代码中的`from gi.repository import Gtk`是不是应该这样安装这个包？  建议搞个requirement.txt  还有我觉得你应该知道python的virtualenv，我就不卖弄了。

**Comment by LiuLang** [comment]
On 03/14/2015 09:42 AM, gshmu wrote:
> flac使用是正常的，是设置后保存会报错。
> log：`WARNING module `mutagen` was not found!`  我手动装了mutagen包还是报错。 可能是这个包的依赖问题。
>
> 我安装了deb是好的，正常工作，我多装了个包：`sudo pip3 install gi` 然后就挂了
>> ~$ kwplayer
> Traceback (most recent call last):
>    File "/usr/bin/kwplayer", line 13, in <module>
>      from gi.repository import Gtk
>    File "/usr/local/lib/python3.4/dist-packages/gi/__init__.py", line 39
>      print url
>              ^
> SyntaxError: invalid syntax
>
>
> 卸载这个包就正常了，是不是这个包我装的有问题？ 代码中的`from gi.repository import Gtk`是不是应该这样安装这个包？  建议搞个requirement.txt  还有我觉得你应该知道python的virtualenv，我就不卖弄了。
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/LiuLang/kwplayer/issues/78#issuecomment-79667887
>
mutagenx 这个包是处理ID3乱码的, 它不是必须的, 也可以不安装.

**Comment by LiuLang** [comment]
On 03/14/2015 09:42 AM, gshmu wrote:
> flac使用是正常的，是设置后保存会报错。
> log：`WARNING module `mutagen` was not found!`  我手动装了mutagen包还是报错。 可能是这个包的依赖问题。
>
> 我安装了deb是好的，正常工作，我多装了个包：`sudo pip3 install gi` 然后就挂了
>> ~$ kwplayer
> Traceback (most recent call last):
>    File "/usr/bin/kwplayer", line 13, in <module>
>      from gi.repository import Gtk
>    File "/usr/local/lib/python3.4/dist-packages/gi/__init__.py", line 39
>      print url
>              ^
> SyntaxError: invalid syntax
>
>
> 卸载这个包就正常了，是不是这个包我装的有问题？ 代码中的`from gi.repository import Gtk`是不是应该这样安装这个包？  建议搞个requirement.txt  还有我觉得你应该知道python的virtualenv，我就不卖弄了。
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/LiuLang/kwplayer/issues/78#issuecomment-79667887
>

你先把~/.config/kuwo/kwplayer.log 和kwplayer-stderr.log 删除了, 再重新测 
试一下, 看看是否还出错, 如果出错, 请把那两个log文件的内容贴出来我看看.

**Comment by mhohai** [comment]
我设置关闭时总会报错，log里会报import错误。  不知道在本地怎么调试，所以没能精确定位错误。
![](https://clbin.com/6r5s0N.png)
你用irc不？ 进下#zh-cn  指点下如何在本地调试环境

**Comment by LiuLang** [comment]
On 03/14/2015 09:52 AM, gshmu wrote:
> 我设置关闭时总会报错，log里会报import错误。  不知道在本地怎么调试，所以没能精确定位错误。
> ![](https://clbin.com/6r5s0N.png)
> 你用irc不？ 进下#zh-cn  指点下如何在本地调试环境
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/LiuLang/kwplayer/issues/78#issuecomment-79680683
>

这个错误是已经修复了的, 在3.5.1中.
现在你用的是3.4.9吧

**Comment by LiuLang** [comment]
https://github.com/LiuLang/kwplayer/commit/2519bfc50e6db955a0e828ee91b17810763bbd08

**Comment by mhohai** [comment]
是，我的错

**Comment by LiuLang** [comment]
这个没关系啦, 等我今天推了v3.5.2后你直接升级就可以 ;-)

**Comment by mhohai** [comment]
我有个疑问：装deb 和 源码 一起使用有共存问题么？
如何直接用源码，那个`from gi.repository import Gtk` 我装上gi包还是灰的，是不是装的不对？

**Comment by LiuLang** [comment]
使用pip命令安装时, 它会做检测的, 如果已经安装过, 它就会报错.
python3-gi 这个包不需要手动安装的

**Comment by mhohai** [comment]
这个是python包啊，我直接在github pull的源代码，谢谢了
