### ISSUE TITLE
HISTORY中最近三次更新的年份错误

### ISSUE THREAD

**Issue by zhcj** [LiuLang/kwplayer#79]
应为2015，都写成了2014

**Comment by LiuLang** [comment]
On 03/18/2015 11:16 AM, zhcj wrote:
> 应为2015，都写成了2014
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/LiuLang/kwplayer/issues/79
>

这个...确实如此, 当时太粗心了 ;-(
