### ISSUE TITLE
archlinux 上面 vpn 问题. (我不知道在其他的 发行版怎么样......)

### ISSUE THREAD

**Issue by dannyZhou** [LiuLang/kwplayer#82]
我现在 用的 是 archlinux, 上面 为了越过 学校 登陆账号限制. 我弄了一台 server 2008 作为 vpn , 
但是 现在 如果 打开 vpn .  在 使用 kwplayer 播放音乐. 加载明显变慢. 
并 且 经常出现问题. 有时候 甚至报错. 但是关了 vpn 以后 就恢复正常.
server 2008 是 校内的 服务器. 不会存在 访问 kuwo.cn 慢的问题.

**Comment by LiuLang** [comment]
On 05/09/2015 09:58 PM, danny wrote:
> 我现在 用的 是 archlinux, 上面 为了越过 学校 登陆账号限制. 我弄了一台 server 2008 作为 vpn ,
> 但是 现在 如果 打开 vpn .  在 使用 kwplayer 播放音乐. 加载明显变慢.
> 并 且 经常出现问题. 有时候 甚至报错. 但是关了 vpn 以后 就恢复正常.
> server 2008 是 校内的 服务器. 不会存在 访问 kuwo.cn 慢的问题.
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/LiuLang/kwplayer/issues/82
>

你可以试着开启VPN后直接访问kuwo.cn, 看看速度怎么样

**Comment by dannyZhou** [comment]
恩恩 还是网络有问题
